spring:
  web:
    resources:
      static-locations: file:/home/ec2-user/images/
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small

  datasource:
    core:
      jdbc-url: ${CORE_DB_URL}
      username: ${CORE_DB_USERNAME}
      password: ${CORE_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

    vector:
      jdbc-url: ${VECTOR_DB_URL}
      username: ${VECTOR_DB_USERNAME}
      password: ${VECTOR_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
        jdbc:
          batch_size: 100

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}
